default_platform(:ios)

platform :ios do
  desc "Export ipa"
  lane :export_ipa do

    create_keychain(
      name: "ios-build.keychain",
      password: "",
      default_keychain: false,
      unlock: true,
      timeout: 3600
    )

    import_certificate(
    certificate_path: "ios-build.p12",
    certificate_password: ENV["CERTIFICATE_PASSWORD"],
    keychain_name: "ios-build.keychain",
    keychain_password: "",
    log_output: true
    )

    # if ENV["EXTRA_CERTIFICATE"] == 'true'
    #     import_certificate(
    #     certificate_path: "ios-build-extra.p12",
    #     certificate_password: ENV["CERTIFICATE_PASSWORD"],
    #     keychain_name: "ios-build.keychain",
    #     keychain_password: "",
    #     log_output: true
    #     )
    # end
  
    install_provisioning_profile(
      path: "ios-build.mobileprovision"
    )
    disable_targets = ENV["DISABLE_TARGETS"]&.split(/,/)

    update_code_signing_settings(
      use_automatic_signing: false,
      path: ENV["PROJECT_PATH"],      
      code_sign_identity: ENV['CODE_SIGNING_IDENTITY']
    )
    update_project_provisioning(
        xcodeproj: ENV["PROJECT_PATH"],
        profile: "ios-build.mobileprovision",        
    )

    if ENV["EXTRA_PROVISIONING"] == 'true'
        update_project_provisioning(
        xcodeproj: ENV["PROJECT_PATH"],
        target_filter: ENV["TARGET_FILTER"],
        profile: "ios-build-extension.mobileprovision",        
        )
    end

    update_project_team(
      path: ENV["PROJECT_PATH"],
      teamid: ENV["TEAM_ID"]
    )

    if ENV["BUILD_PODS"] == 'true'
      cocoapods(
        podfile: ENV["PODS_PATH"]
      )
    end

    if ENV["WORKSPACE_PATH"] != ""
      build_app(
        workspace: ENV["WORKSPACE_PATH"],
        configuration: ENV["CONFIGURATION"],
        scheme: ENV["SCHEME"],
        output_name: ENV["OUTPUT_PATH"],
        clean: true,
        export_method: ENV["EXPORT_METHOD"]
      )
    else
      build_app(
        project: ENV["PROJECT_PATH"],
        configuration: ENV["CONFIGURATION"],
        scheme: ENV["SCHEME"],
        output_name: ENV["OUTPUT_PATH"],
        clean: true,
        export_method: ENV["EXPORT_METHOD"]
      )
    end
    
    
    delete_keychain(
      name: "ios-build.keychain"
    )
  end
end
